//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTT2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoTT_Hotline_Report_Rawdata
    {
        public int id { get; set; }
        public string Org { get; set; }
        public string Ord_Dt { get; set; }
        public string Req_Dt { get; set; }
        public string Promise_Date { get; set; }
        public string Order_Num { get; set; }
        public string Serv_Ord_Num { get; set; }
        public string Item_Name { get; set; }
        public string Req_Qty { get; set; }
        public string Order_Type { get; set; }
        public string Business { get; set; }
        public string Dest_Org { get; set; }
        public string WH_Status { get; set; }
        public string Backlog_Instr { get; set; }
        public string Ord_Qty { get; set; }
        public string Delivered_Qty { get; set; }
        public string Cancelled_Qty { get; set; }
        public string Schd_Dt { get; set; }
        public string Age { get; set; }
        public string Serv_Req_Num { get; set; }
        public string S_Country { get; set; }
        public string LTB { get; set; }
        public string Order_Type2 { get; set; }
        public string SR_Asset_Serial_Number { get; set; }
        public string MODEL { get; set; }
        public string Item_Type { get; set; }
        public string HWPL { get; set; }
        public string CIRF_ { get; set; }
        public string Line_Number { get; set; }
        public string Pack_Instruction { get; set; }
        public string Ship_Instruction { get; set; }
        public string STATUS { get; set; }
        public string ref_part_num { get; set; }
        public string ref_Status { get; set; }
        public string HOLD_TYPE { get; set; }
        public string SO_Number_S { get; set; }
        public string SO_Type_S { get; set; }
        public string SO_Status_S { get; set; }
        public string PSO_Number { get; set; }
        public string PSO_Status { get; set; }
        public string PSO_Team_S { get; set; }
        public string Employee_Name_S { get; set; }
        public string SO_Organization_S { get; set; }
        public string SO_Region_S { get; set; }
        public string SR_Agilent_Model_Number_S { get; set; }
        public string SR_Asset_Serial_Number_S { get; set; }
        public string RM_Comments { get; set; }
        public string Supplier { get; set; }
        public string Delay_Reason { get; set; }
        public string Logistics_Delay_Reasons { get; set; }
        public Nullable<System.DateTime> RM_Comment_date { get; set; }
        public string RM_Comment_User { get; set; }
        public string RM_Coordinator_Email { get; set; }
        public string RM_Coordinator_Name { get; set; }
        public string EOS_DATE { get; set; }
        public string Reserved_Qty { get; set; }
        public string K02_OH { get; set; }
        public string K03_OH { get; set; }
        public string K04_OH { get; set; }
        public string K02_InTransit_Qty { get; set; }
        public string K03_InTransit_Qty { get; set; }
        public string K04_InTransit_Qty { get; set; }
        public string Korg_FIXME_Qty { get; set; }
        public string Korg_QACHECK_Qty { get; set; }
        public string ref_EOS { get; set; }
        public string K02_ref_OH { get; set; }
        public string K03_ref_OH { get; set; }
        public string K04_ref_OH { get; set; }
        public string K02_ref_InTransit_Qty { get; set; }
        public string K03_ref_InTransit_Qty { get; set; }
        public string K04_ref_InTransit_Qty { get; set; }
        public string Korg_ref_FIXME_Qty { get; set; }
        public string Korg_ref_QACHECK_Qty { get; set; }
        public string Line_type { get; set; }
        public string DEST_LOC_CD { get; set; }
        public string PRODUCT_HEIRARCHY { get; set; }
        public string Deliver_to { get; set; }
        public string Item_Description { get; set; }
        public string Order_Source_Ref { get; set; }
        public string Org_Name { get; set; }
        public string REQ_Age_WD { get; set; }
        public string Line_Status { get; set; }
        public string Line_Id { get; set; }
        public string Un_List_Pr { get; set; }
        public string Un_Sell_Pr { get; set; }
        public string Ship_to { get; set; }
        public string Sub_Inv { get; set; }
        public string Pick_Qty { get; set; }
        public string S_City { get; set; }
        public string S_Loc_Id { get; set; }
        public string S_Post_Code { get; set; }
        public string Load_Date { get; set; }
        public string Site_Number { get; set; }
        public string Address4 { get; set; }
        public string Ship_Set { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Number { get; set; }
        public string Cust_PO_Num { get; set; }
        public string SPR_Address { get; set; }
        public string booked_dt { get; set; }
        public string K02_Buyer { get; set; }
        public string K02_Supplier { get; set; }
        public string K03_Buyer { get; set; }
        public string K03_Supplier { get; set; }
        public string K04_Buyer { get; set; }
        public string K04_Supplier { get; set; }
        public string DataTimestamp { get; set; }
        public string Age_Group { get; set; }
        public string Destination_Sub { get; set; }
        public string DC_2_DC { get; set; }
        public string Demand_K02 { get; set; }
        public string Demand_K03 { get; set; }
        public string Demand_K04 { get; set; }
        public string PrimaryExcess { get; set; }
        public string Prob_Bklg { get; set; }
        public string Due { get; set; }
        public string demand_freq { get; set; }
        public string K02_PROCESSING_LEAD_TIME { get; set; }
        public string K03_PROCESSING_LEAD_TIME { get; set; }
        public string K04_PROCESSING_LEAD_TIME { get; set; }
        public string Tab_Name { get; set; }
        public string PLANNER { get; set; }
        public string PLANNER_CODE { get; set; }
        public string Ship_Method { get; set; }
        public string Ship_To_Loc { get; set; }
        public string W68_OH { get; set; }
        public string W68_Intransit_Qty { get; set; }
        public string Priority_Code { get; set; }
        public string IR { get; set; }
        public string ISO { get; set; }
    }
}
